name: Sync Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/WIKI_DEPLOY_CLOUD.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dibutuhkan untuk push ke wiki
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Kita hanya mensinkronkan folder docs
          wiki_folder: docs
          # File WIKI_DEPLOY_CLOUD.md akan menjadi halaman bernama "WIKI DEPLOY CLOUD" di Wiki
          # Jika ingin otomatis membersihkan file lama di wiki yang tidak ada di docs, gunakan true
          clean_wiki_directory: false
